### ISSUE TITLE
add support

### ISSUE THREAD

**Issue by Ghostleader1399** [Ifera/ScoreHudX#20]
can you add PiggyFactions support?

**Comment by AIPTU** [comment]
https://rtdx.aericio.net/en/latest/plugins/piggyfactions/docs/addons.html#scorehud-v6

**Comment by Ifera** [comment]
As mentioned by @AIPTU and mentioned and numerous places in the readme, ScoreHud v6 no longer needs to provide in-built support for other plugins. Plugin developers can integrate ScoreHud into their own plugins providing out-of-box support for ScoreHud with no additional plugin(s) needed. As is done by PiggyFactions.
