### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by GamerMJay** [Ifera/ScoreHudX#26]
Pls Change EconomyAPI to BedrockEconomy

**Comment by Ifera** [comment]
Please ask the author of BedrockEconomy plugin to add support for ScoreHud into their plugin or provide a plugin that adds support for scorehud.

**Comment by TukangM** [comment]
BasicScore is ScoreHudX?

**Comment by TukangM** [comment]
is there a basic score for pm4?

> BasicScore is ScoreHudX?



> Please ask the author of BedrockEconomy plugin to add support for ScoreHud into their plugin or provide a plugin that adds support for scorehud.

**Comment by TukangM** [comment]
> Pls Change EconomyAPI to BedrockEconomy



> Please ask the author of BedrockEconomy plugin to add support for ScoreHud into their plugin or provide a plugin that adds support for scorehud.

source : https://github.com/cooldogedev/BedrockEconomy#scorehud-integration

Available Tags
{bedrockeconomy.balance}
{bedrockeconomy.balance_cap}
{bedrockeconomy.currency_symbol}
{bedrockeconomy.currency_name}
