### ISSUE TITLE
More tags/event

### ISSUE THREAD

**Issue by BLAST1718** [Ifera/ScoreHudX#3]
Pls add more like for pureperms and skyblock

**Comment by callumrawlinson** [comment]
Like what @BLAST1718

**Comment by BLAST1718** [comment]
like for skyblock and pureprms

**Comment by Ifera** [comment]
I will do for PurePerms cause thats not being maintained actively and a lot of people use it. I wont be doing for SkyBlock. So go ask the author of that SkyBlock plugin to provide tags for ScoreHud. PurePerms is the only exception.

**Comment by callumrawlinson** [comment]
How do you add a timer?
