### ISSUE TITLE
i have now the Binaries

### ISSUE THREAD

**Issue by galaxytwenty** [Ifera/ScoreHudX#4]
but this comes now:

[19:17:59] [Server thread/CRITICAL]: Error: "Class 'Ifera\ScoreHud\event\ServerTagsUpdateEvent' not found" (EXCEPTION) in "plugins/BasicScore/src/Ifera/BasicScore/Main" at line 33

how to fix ?

**Comment by galaxytwenty** [comment]
**Okay** with the new **Dev** version it works, **sry for open an issue**. by the **PurePermsScore** is the rank **shows only** in the **color** what i **set in the config**. can u made this that the rank shows in the **color** what i have set in the **config** from **pureperms** ?.

**Best Greeeeeetz**

**Comment by Ifera** [comment]
> but this comes now:
> 
> [19:17:59] [Server thread/CRITICAL]: Error: "Class 'Ifera\ScoreHud\event\ServerTagsUpdateEvent' not found" (EXCEPTION) in "plugins/BasicScore/src/Ifera/BasicScore/Main" at line 33
> 
> how to fix ?

Umm.. The dev build and the latest release are both the same thing. You probably had an outdated release of ScoreHud.

**Comment by Ifera** [comment]
> **Okay** with the new **Dev** version it works, **sry for open an issue**. by the **PurePermsScore** is the rank **shows only** in the **color** what i **set in the config**. can u made this that the rank shows in the **color** what i have set in the **config** from **pureperms** ?.
> 
> The New Version Is great, the timming when the setting refresh is likely :)
> 
> **Best Greeeeeetz**

That won't be possible due to API limitations. You will have to set the color in the scorehud config for it to show up on the Scoreboard. Won't work the other way around.

And glad you liked it. :)

**Comment by galaxytwenty** [comment]
Yeah The new is rly fine about the flicker = 0Flicker by me
