### ISSUE TITLE
Me Again. with a question.

### ISSUE THREAD

**Issue by galaxytwenty** [Ifera/ScoreHudX#6]
uhm. can u make that ScoreHud Refresh only the Line who Needed ?.

I have the Problem that when Refresh one line in scorehud, all the scorehud is flickering.
maybe you can make that only one line is flickering when ist refreshd ?

BTW: Maybe you can add a Refresh Timer in The Config for each line ?.
so, when i have a Plugin like OnlineTimer Then Refresh the Board every 1 second, this is Flickering pure !.

**THX** and Healthy in this timings -_-

**Comment by Ifera** [comment]
> uhm. can u make that ScoreHud Refresh only the Line who Needed ?

It already does this.

> I have the Problem that when Refresh one line in scorehud, all the scorehud is flickering.
maybe you can make that only one line is flickering when ist refreshd ?

Try the latest dev build. It should remove the flickering to some extent.

> BTW: Maybe you can add a Refresh Timer in The Config for each line ?.
so, when i have a Plugin like OnlineTimer Then Refresh the Board every 1 second, this is Flickering pure !.

Sorry, not possible.

**Comment by galaxytwenty** [comment]
Okay i use the dev 60, but this flickering is extremly with my scribed score for Onlinetime or when you switch fast the ItemID

if even a small thing changes, the whole board flickers... i update from v5 in hope the flickering was removed. i mean yea its better but not removed sometime flickering harder then before. 

for Only Reasons have you Discord ?.
Thx for your answer and GreatJob

**Comment by Ifera** [comment]
There is nothing more that can be done, given the current API. I personally have tested this and there is no flickering of scoreboard on my end, Might be that the machine you are using or that your connection is slow. Or maybe that OnlineTime is causing it. Other than that, nothing more can be done right now.
